module.exports = {
  developer: 'Anigami',
  ownerID: '197673134885699585',
  token: 'ODM1NDMzMDQyOTA2MTg1NzY4.YIPXpw.QoE3s7_jGEiyyRwOlNnvFTsyJpw',
  prefix: '!',
  mongodburi: 'mongodb+srv://anigami:Aa561197@cluster0.qoobr.mongodb.net/christian?retryWrites=true&w=majority',
  database: 'christian',
  collection: {
    ban: 'ban',
    mute: 'mute',
    warn: 'warn',
    modstats: 'modstats',
    config: 'config',
    reactrole: 'reactrole',
    giveaway: 'giveaway',
    userdata: 'userdata',
    userlogs: 'userlogs',
    lotterysmall: 'lotterysmall',
    lotterymedium: 'lotterymedium',
    lotterylarge: 'lotterylarge',
  },
  lotterysmallbase: 3000,
  lotterymediumbase: 10000,
  lotterylargebase: 100000,
  lotterysmallprice: 50,
  lotterymediumprice: 1000,
  lotterylargeprice: 10000,
};
